repos:
- repo: local
  hooks:
  - id: forbid_prints
    name: Check for leftover print statements.
    types: [python]
    entry: "print\\s*\\("
    language: pygrep
- repo: local
  hooks:
  - id: no-todos
    name: Forbid TODOs
    entry: "TODO"
    language: pygrep
    types: [python]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.4
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
  - id: mypy
    name: Run type checks
    args: ["--ignore-missing-imports"]
    additional_dependencies: ["types-setuptools"]
- repo: local
  hooks:
  - id: gitchangelog
    language: python
    additional_dependencies: ["gitchangelog", "pystache"]
    always_run: true
    pass_filenames: false
    name: Generate changelog
    entry: bash -c "gitchangelog > CHANGELOG.md"
    stages: [commit]
- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    entry: pytest
    language: system
    pass_filenames: false
    always_run: true
